language: node_js

node_js:
  - "8"

services:
  - docker

cache: npm

script:
  - npm test
  - npm run lint

jobs:
  include:
    - stage: npm release
      if: tag IS present
      node_js: "8"
      script: npm i
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          tags: true