name: "Main"
on:
  pull_request:
  push:
    tags:
      - "*"
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-16.04
    strategy:
      fail-fast: false # don't cancel all jobs if some of them failed
      matrix:
        node: ["10", "12"]
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: yarn install
      - run: yarn lint
      - run: yarn test
      - name: Test ncc build (for Github Actions)
        run: yarn ncc

  test-as-action:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
      - run: yarn install
      - run: yarn build
      # Simulate Github Actions run
      - name: Setup a mock package to test locally
        run: node dist/dappnodesdk.js init --yes --force
      - name: Build and post comment
        run: node dist/dappnodesdk.js build --upload_to ipfs --provider pinata --require_git_data --delete_old_pins

  release:
    runs-on: ubuntu-latest
    needs: [test, test-as-action]
    if: github.event_name == 'push' && github.ref != 'refs/heads/master' && contains(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
          registry-url: https://registry.npmjs.org/
      - run: yarn install
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
